"""Example: Federated AutoML with TS1 (Temporal Split) partitioning.

Mirrors :mod:`federated_automl_example` exactly -- synthetic multi-
series TS generated by :class:`TimeSeriesDatasetsGenerator`, binary
classification, ``data_type='time_series'``. The only difference is
``partitioning_method='temporal'`` in ``strategy_params``: RAF splits
the sample axis into ``n_splits`` contiguous blocks, and each worker
trains on a disjoint slice.

Why ``data_type='time_series'`` instead of the windowed-regression
setup used in the M4 helpers: Industrial's TS pipeline knows how to
feed ``(n_samples, ts_len)`` matrices to its forecasters / classifiers
directly, so ``convert_to_torch_format`` doesn't assert on the
intermediate 2-D shape.

Tunable ``partitioning_params`` for ``'temporal'``:

* ``overlap``: fraction of chunk length reused from the preceding
  block (default 0 -- disjoint).
* ``min_chunk_size``: floor on per-chunk sample count; ``n_splits``
  is reduced automatically if the dataset is too small.
"""
from fedot_ind.core.architecture.pipelines.abstract_pipeline import ApiTemplate
from fedot_ind.core.repository.config_repository import (
    DEFAULT_AUTOML_LEARNING_CONFIG,
    DEFAULT_CLF_AUTOML_CONFIG,
    DEFAULT_COMPUTE_CONFIG,
)
from fedot_ind.tools.synthetic.ts_datasets_generator import TimeSeriesDatasetsGenerator


def run_temporal_split_federated_ts_example(timeout: int = 10,
                                            num_samples: int = 1800,
                                            max_ts_len: int = 50,
                                            overlap: float = 0.0):
    industrial_config = {
        'problem': 'classification',
        'learning_strategy': 'federated_automl',
        'strategy': 'federated_automl',
        'strategy_params': {
            'timeout': timeout,
            'data_type': 'time_series',
            'problem': 'classification',
            'partitioning_method': 'temporal',
            'partitioning_params': {
                'overlap': overlap,
                'min_chunk_size': 50,
            },
        },
    }

    learning_config = {
        'learning_strategy': 'from_scratch',
        'learning_strategy_params': {**DEFAULT_AUTOML_LEARNING_CONFIG, 'timeout': timeout},
        'optimisation_loss': {'quality_loss': 'f1'},
    }

    api_config = {
        'industrial_config': industrial_config,
        'automl_config': DEFAULT_CLF_AUTOML_CONFIG,
        'learning_config': learning_config,
        'compute_config': DEFAULT_COMPUTE_CONFIG,
    }

    train_data, test_data = TimeSeriesDatasetsGenerator(
        num_samples=num_samples,
        task='classification',
        max_ts_len=max_ts_len,
        binary=True,
        test_size=0.5,
        multivariate=False,
    ).generate_data()

    dataset_dict = dict(train_data=train_data, test_data=test_data)
    result_dict = ApiTemplate(
        api_config=api_config,
        metric_list=('f1', 'accuracy'),
    ).eval(dataset=dataset_dict, finetune=False)

    return result_dict


if __name__ == '__main__':
    result = run_temporal_split_federated_ts_example(timeout=2)
    print(result)
